### ISSUE TITLE
Ordering based on mapped DTO

### ISSUE THREAD

**Issue by MrNickGreene** [mrahhal/MR.EntityFrameworkCore.KeysetPagination#21]
Would it at all be possible to base the `builderAction` parameter off of the mapped DTO (if present), instead of the source entities?

Wonder if this would help alleviate the "nested type" issue someone else raised.

**Comment by mrahhal** [comment]
That's impossible, as the builder action is what tells us how to reach the columns in the model to be able to build the keyset query. The DTO can be a flattened version, etc. Can't use it to build the keyset. This would be the same as expecting EF Core to be able to work with DTOs instead of entities.
