### ISSUE TITLE
Add Enum support in keyset

### ISSUE THREAD

**Issue by CaminGui** [mrahhal/MR.EntityFrameworkCore.KeysetPagination#29]
As a developer I want to be able to use an Enum property in keyset.

Actually this throw an Exception at EF core side.

```cs
public enum MyEnum : int
{
    Val1,
    Val2
}

public class MyEntity
{
    public int Id { get; set; }
    public MyEnum MyEnum { get; set; }
}

var context = query.KeysetPaginate(b => b.Ascending(entity => entity.MyEnum), KeysetPaginationDirection.Forward);
```

Keep in mind that enum order will depend on the way it is stored in Db: string with converter / int ...

**Comment by mrahhal** [comment]
I would definitely like to support enums. Feel free to submit the PR for this and I'll review it.

> Keep in mind that enum order will depend on the way it is stored in Db: string with converter / int ...

This shouldn't matter because we only generate expressions for EF, we're db agnostic. We're only concerned with generating the equivalent EF query that would have worked if written by hand (and that does for enums), the user is the one to be concerned with their db semantics.
