### ISSUE TITLE
Expose KeysetPaginationBuilder.ConfigureColumn

### ISSUE THREAD

**Issue by dheardal** [mrahhal/MR.EntityFrameworkCore.KeysetPagination#50]
Can I change the access modifier on `KeysetPaginationBuilder.ConfigureColumn` to public?

At the moment I am having to write twice the amount of code required to use the fluent methods ascending/descending which I wouldn't need to do if I could just pass in true/false for descending

If not could i create a new method that takes in `System.ComponentModel.ListSortDirection` ?

**Comment by dheardal** [comment]
I ended up doing as you say and writing an extension method around it.

I disagree that in the vast majority of cases you wouldn't use it, since order direction is usually passed through as an API parameter most implementations of this would need to write an extension method to call the right method which is kind of annoying given there is a perfectly good method already!

**Comment by mrahhal** [comment]
If you have a dynamic direction on each request, this still wouldn't be used if you're using [prebuilt definitions](https://github.com/mrahhal/MR.EntityFrameworkCore.KeysetPagination?tab=readme-ov-file#prebuilt-keyset-query-definition) (which is the recommended way). If you're not prebuilding the definitions, then yes I assume in this particular case you would benefit from having one method with an arg for the direction. That's why a code snippet from your use case always helps.

I might need to convert the direction into an enum before making it public since a boolean here would be too opaque. So I'll hold off on the PR until I do that (unless if you want to attempt and do this in the PR, adding a new `KeysetColumnDirection` enum, and processing the changes in the code), I'll keep this issue open.

**Comment by dheardal** [comment]
Unless I'm mistaken, this is using the prebuilt definitions, and would benefit with having one method with an arg:

`    public static KeysetQueryDefinition<TEntity> GetPagingQueryDefinition<TEntity, T>(
        this PagingRequest pagingRequest,
        Expression<Func<TEntity, T>> columnAccessor,
        ListSortDirection defaultOrderDirection = ListSortDirection.Ascending)
        where T : IComparable, IComparable<T>
    {
        return (pagingRequest.OrderDirection ?? defaultOrderDirection) == ListSortDirection.Ascending ?
            KeysetQuery.Build<TEntity>(b => b.Ascending(columnAccessor)) :
            KeysetQuery.Build<TEntity>(b => b.Descending(columnAccessor));
    }`

**Comment by dheardal** [comment]
For reference this is the extension method I built:

```
    public static KeysetQueryDefinition<TEntity> GetPagingQueryDefinition<TEntity, T>(
        this PagingRequest pagingRequest,
        Expression<Func<TEntity, T>> columnAccessor,
        ListSortDirection defaultOrderDirection = ListSortDirection.Ascending)
        where T : IComparable, IComparable<T>
    {
        return (pagingRequest.OrderDirection ?? defaultOrderDirection) == ListSortDirection.Ascending ?
            KeysetQuery.Build<TEntity>(b => b.Ascending(columnAccessor)) :
            KeysetQuery.Build<TEntity>(b => b.Descending(columnAccessor));
    }
```

Quite hard to use prebuilt definitions for user defined requests :)

**Comment by mrahhal** [comment]
> Unless I'm mistaken, this is using the prebuilt definitions, and would benefit with having one method with an arg:

You're creating a new definition each time you call this method, so this isn't using prebuilt definitions correctly. I'm guessing you're calling this method in the action? As I mention in the README, you should put the result of `KeysetQuery.Build` into a long lived instance to use it properly.

In any case, it's true that it's not always feasible to use a prebuilt definition.

**Comment by mrahhal** [comment]
Release in v1.4.0.
